# ===============================
# PROD CONFIGURATION
# ===============================
spring.application.name=lazyops
banner.location=classpath:banner-prod.txt

# External Tomcat will set the port
#server.port not required here

# Database (prod Postgres)
spring.datasource.url=jdbc:postgresql://prod-db:5432/lazydb
spring.datasource.username=lazyops_prod
spring.datasource.password=superSecurePwd
spring.datasource.driver-class-name=org.postgresql.Driver

# Do not auto-create tables in production
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Connection Pool (bigger in prod)
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5

# Logging (lighter in prod)
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=INFO

